# Acquire port
com.hp.acquire:
    #disable  dataServer and dataHandler .if set this value true,neither dataServer nor dataHandler will work
    disabled: true
    #disable  dataServer.if set this value true,dataServer will not work
    dataserver-disabled: true
    #disable  dataHandler.if set this value true,dataHandler will not work
    datahandler-disabled: true
    # if this server work as a dataserver,it will only save the data with the specified suffix in redis,eg.value 1,2  the redis keys: input1:vin  input2:vin
    dataserver-realTimeDataSuffix: 1,2,3,4,5,6,7,8,9,10
    # save the warningData with specified suffix in redis,eg.value wr  the redis keys: inputwr:vin
    dataserver-warningDataSuffix: wr
    # if this server work as a data handler,it will only handle the data with the specified suffix in redis.eg.value 1,2 or ALL（handle all "input*" datas）
    datahandler-handleSuffix: ALL
    #data server listen on this port
    port: 9000
    nettyServerThreadPoolSize: 10
    nettyServerTcpBacklog: 1024
    dataHandlerThreadPoolSize: 10

com.hp.mqtt:
    queueName: queue
    host: 127.0.0.1
    port: 5672
    userName:
    password:
# apns cer password
com.hp.apns.cer.password:

# apns p12 file path
com.hp.apns.p12:

# com.hp.push.url
com.hp.push.url:

# com.hp.web.server.host
com.hp.web.server.host: 127.0.0.1

# com.hp.web.server.baiduKey
com.hp.web.server.baiduKey:

# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN

# Spring settings
spring:
    profiles.active: dev
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/briair?characterEncoding=utf8
        username: javapp
        password:
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        database: 0
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1