# Acquire port
com.hp.acquire:
    #disable  dataServer and dataHandler .if set this value true,neither dataServer nor dataHandler will work
    disabled: true
    #disable  dataServer.if set this value true,dataServer will not work
    dataserver-disabled: true
    #disable  dataHandler.if set this value true,dataHandler will not work
    datahandler-disabled: true
    #datahandler-heartbeat-interval  (seconds) by default 10s ,the data handler will loop sent heartbeat signal.by this, the data server will sent data to these groups
    datahandler-heartbeat-interval: 10
    #datahandler-heartbeat-ttl  the ttl for key in redis,if a server suspend,after ttl,no data will be send to this group
    datahandler-heartbeat-ttl: 12
    # save the warningData with specified suffix in redis,eg.value wr  the redis keys: inputwr:<vin>
    dataserver-warningDataSuffix: wr
    # if this server work as a data handler,it will only handle the data with the specified suffix in redis.eg.value 1,2 or ALL
    datahandler-handleSuffix: ALL
    #data server listen on this port
    port: 9000
    nettyServerThreadPoolSize: 20
    nettyServerTcpBacklog: 100000
    dataHandlerThreadPoolSize: 20
    dataHandlerMaxCount: 300 #实时数据每次处理数据量

#remoteControl maxDistance
com.hp.remoteControl.maxDistance: 2000

#remoteControl maxDistance
com.hp.remoteControl.maxCount: 3

com.hp.mqtt:
    queueName: queue
    host: 127.0.0.1
    port: 5672
    userName:
    password:
# apns cer password
com.hp.apns.cer.password:

# apns p12 file path
com.hp.apns.p12:

# com.hp.push.url
com.hp.push.url: http://localhost:8080/api/message/filePush

# com.hp.web.server.host
com.hp.web.server.host: 127.0.0.1

# com.hp.web.server.baiduKey
com.hp.web.server.baiduKey:

# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN

# Spring settings
spring:
    profiles.active: dev
    datasource:
        max-active: 100
        max-idle: 40
        min-idle: 35
        url: jdbc:mysql://127.0.0.1:3306/briair?characterEncoding=utf8&rewriteBatchedStatements=true
        username: javapp
        password:
        auto-commit: true
    jpa:
        show-sql: false
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        database: 0
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1