update t_warning_message_conversion set group_message_en='Airbag System Fault' where group_id=1;
update t_warning_message_conversion set group_message_en='Electrical Steering Column Lock Fault' where group_id=2;
update t_warning_message_conversion set group_message_en='Body Control Module Fault' where group_id=3;
update t_warning_message_conversion set group_message_en='Electronic Stability Control Fault' where group_id=4;
update t_warning_message_conversion set group_message_en='Brake System Fault' where group_id=5;
update t_warning_message_conversion set group_message_en='Transmission Fault' where group_id=6;
update t_warning_message_conversion set group_message_en='Engine Fault' where group_id=7;
update t_warning_message_conversion set group_message_en='Antilock Brake System Fault' where group_id=8;
update t_warning_message_conversion set group_message_en='Electric Power Steering Fault' where group_id=9;
update t_warning_message_conversion set group_message_en='Keyless Entry System Fault' where group_id=10;
update t_warning_message_conversion set group_message_en='Tire Pressure Monitoring System Fault' where group_id=11;
update t_warning_message_conversion set group_message_en='Park Distance Control Fault' where group_id=12;
update t_warning_message_conversion set group_message_en='Blind Spot Monitoring System Fault' where group_id=13;
update t_warning_message_conversion set group_message_en='E-hand Brake Fault' where group_id=14;
update t_warning_message_conversion set group_message_en='Hill Decent Control Fault' where group_id=15;
update t_warning_message_conversion set group_message_en='Cruise Control Fault' where group_id=16;
update t_warning_message_conversion set group_message_en='Start-Stop System Fault' where group_id=17;
update t_warning_message_conversion set group_message_en='Charge System Fault' where group_id=18;
update t_warning_message_conversion set group_message_en='Autohold System Fault' where group_id=19;
update t_warning_message_conversion set group_message_en='Hill Start Assist Malfunction Fault' where group_id=20;
update t_warning_message_conversion set group_message_en='Gear Shift Fault' where group_id=21;
update t_warning_message_conversion set group_message_en='Electric Tail Gate Fault' where group_id=22;
update t_warning_message_conversion set group_message_en='Front Crash Warning Fault' where group_id=23;
update t_warning_message_conversion set group_message_en='Emergency Brake System Fault' where group_id=24;
update t_warning_message_conversion set group_message_en='Lane Departure Warning System Fault' where group_id=25;