CREATE TABLE IF NOT EXISTS t_drive_behavior_report (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  type smallint(5) DEFAULT 0 COMMENT '1天 2周 3月',
  year varchar(10) NOT NULL COMMENT '年',
  month smallint(5) DEFAULT 0 COMMENT '月份',
  week smallint(5) DEFAULT 0 COMMENT '第多少周',
  date_string varchar(10) DEFAULT NULL COMMENT '日期字符串 2017-01-05',
  brand varchar(20) DEFAULT NULL COMMENT '品牌',
  model varchar(20) DEFAULT NULL COMMENT '车型',
  vin varchar(50) NOT NULL COMMENT 'vin',
  run_times bigint(20) NOT NULL DEFAULT 0 COMMENT '运行时间 单位秒',
  out_times int(11) NOT NULL DEFAULT 0 COMMENT '出行次数',
  sudden_up int(11) NOT NULL DEFAULT 0 COMMENT '急加速次数',
  sudden_dec int(11) NOT NULL DEFAULT 0 COMMENT '急减速次数',
  sudden_turn int(11) NOT NULL DEFAULT 0 COMMENT '急转弯次数',
  tire_drive_times int(11) NOT NULL DEFAULT 0 COMMENT '疲劳驾驶次数',
  speeding_drive bigint(20) NOT NULL DEFAULT 0 COMMENT '超速时间 单位秒',
  max_speed smallint(5) DEFAULT 0 COMMENT '最高超速速度 公里/小时',
  avg_oil float DEFAULT 0 COMMENT '平均油耗',
  mail_range int(11) NOT NULL DEFAULT 0 COMMENT '累计行驶里程',
  drive_time1 int(11) NOT NULL DEFAULT 0 COMMENT '1速段行驶时间　秒',
  drive_time2 int(11) NOT NULL DEFAULT 0 COMMENT '1-45速段行驶时间 秒',
  drive_time3 int(11) NOT NULL DEFAULT 0 COMMENT '40-90速段行驶时间 秒',
  drive_time4 int(11) NOT NULL DEFAULT 0 COMMENT '90以上速段行驶时间 秒',
  traffic_gridlock_times int(11) NOT NULL DEFAULT 0 COMMENT '早晚高峰出行次数',
  daybreak_out_times int(11) NOT NULL DEFAULT 0 COMMENT '凌晨出行次数',
  score int(11) NOT NULL DEFAULT 0 COMMENT '评分',
  suggestion varchar(50) DEFAULT NULL COMMENT '专家建议',
  PRIMARY KEY (id),
  INDEX idx_vin(vin)
) DEFAULT CHARSET=utf8 COMMENT='驾驶行为分析汇总表';

