CREATE TABLE  t_data_diagnostic (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  vin varchar(17) NOT NULL COMMENT '车架号',
  event_id bigint(20) NOT NULL COMMENT 'event id',
  has_ack smallint(1) NOT NULL COMMENT '是否响应',
  dia_cmd_data_size smallint(2) NOT NULL COMMENT '是否响应',
  dia_number smallint(2) NOT NULL COMMENT '是否响应',
  dia_id smallint(2) NOT NULL COMMENT '是否响应',
  send_date DATETIME NOT NULL COMMENT '发送时间',
  receive_date DATETIME  COMMENT '接收时间',
  message1 varchar(50)  COMMENT 'message1',
  message2 varchar(50)  COMMENT 'message2',
  message3 varchar(50)  COMMENT 'message3',
  message4 varchar(50)  COMMENT 'message4',
  message5 varchar(50)  COMMENT 'message5',
  message6 varchar(50)  COMMENT 'message6',
  message7 varchar(50)  COMMENT 'message7',
  message8 varchar(50)  COMMENT 'message8',
  message9 varchar(50)  COMMENT 'message9',
  message10 varchar(50)  COMMENT 'message10',
  message11 varchar(50)  COMMENT 'message11',
  message12 varchar(50)  COMMENT 'message12',
  message13 varchar(50)  COMMENT 'message13',
  message14 varchar(50)  COMMENT 'message14',
  message15 varchar(50)  COMMENT 'message15',
  message16 varchar(50)  COMMENT 'message16',
  message17 varchar(50)  COMMENT 'message17',
  PRIMARY KEY (id)
) DEFAULT CHARSET=utf8 COMMENT='诊断数据表';