CREATE TABLE  t_data_diagnostic (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  vin varchar(17) NOT NULL COMMENT '车架号',
  event_id bigint(20) NOT NULL COMMENT 'event id',
  has_ack smallint(1) NOT NULL COMMENT '是否响应',
  send_date DATETIME NOT NULL COMMENT '发送时间',
  receive_date DATETIME  COMMENT '接收时间',
  message1 smallint(1)  COMMENT '发动机/变速器系统 1异常 0正常',
  message2 smallint(1)  COMMENT '安全气囊系统 1异常 0正常',
  message3 smallint(1)  COMMENT '制动防抱死系统 1异常 0正常',
  message4 smallint(1)  COMMENT '车联网系统 1异常 0正常',
  message5 smallint(1)  COMMENT '机油压力 1异常 0正常',
  message6 smallint(1)  COMMENT '车身稳定系统 1异常 0正常',
  message7 smallint(1)  COMMENT '排放系统 1异常 0正常',
  message8 smallint(1)  COMMENT '充电系统 1异常 0正常',
  message9 smallint(1)  COMMENT '能量 1异常 0正常',
  message10 smallint(1)  COMMENT '仪表系统 1异常 0正常',
  message11 smallint(1)  COMMENT '多向可调电控座椅系统 1异常 0正常',
  message12 smallint(1)  COMMENT '电动转向系统 1异常 0正常',
  message13 smallint(1)  COMMENT '网关系统 1异常 0正常',
  message14 smallint(1)  COMMENT '停车辅助装置 1异常 0正常',
  message15 smallint(1)  COMMENT '胎压监测系统 1异常 0正常',
  message16 smallint(1)  COMMENT '电子巡航系统故障 1异常 0正常',
  PRIMARY KEY (id)
) DEFAULT CHARSET=utf8 COMMENT='诊断数据表';