create table t_remote_control(
id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
uid int(11) NOT NULL COMMENT 'uid',
session_id varchar(15) NOT NULL COMMENT'application+eventid拼接成的会话id',
vin varchar(18)  NOT NULL COMMENT 'vin',
sending_time DATETIME NOT NULL COMMENT '发送时间',
control_type smallint(1) NOT NULL COMMENT '控制类别  0：远程启动发动机  1：远程关闭发动机  2：车门上锁  3：车门解锁  4：空调开启  5：空调关闭  6：座椅加热  7：座椅停止加热  8：远程发动机限制  9：远程发动机限制关闭  10：远程寻车',
ac_temperature double(6,2) NOT NULL COMMENT '空调温度(配合type=4)',
light_num smallint(6) DEFAULT 0 COMMENT '闪灯次数，仅在cType=10生效',
horn_num smallint(6) DEFAULT 0 COMMENT '鸣笛时长，仅在cType=10生效',
act_time double(6,2) DEFAULT 0 COMMENT '闪灯鸣笛时长',
de_active smallint(6) DEFAULT 0 COMMENT '关闭闪灯鸣笛，0 无效 1 生效 仅在cType=10生效',
auto_mode smallint(6) DEFAULT 0 COMMENT '空调自动模式 0 手动 1 自动 默认 0',
recir_mode smallint(6) DEFAULT 0 COMMENT '循环模式 0 内循环 1 外循环 默认外循环.仅在cType=4生效',
ac_mode smallint(6) DEFAULT 0 COMMENT 'AC模式  0 关闭压缩机 1 开启压缩机.仅在cType=4生效',
fan smallint(6) DEFAULT 0 COMMENT '风速  范围 1-7.仅在cType=4生效',
mode smallint(6) DEFAULT 0 COMMENT '模式  1除雾 2前玻璃除雾+吹脚 3 吹脚 4吹身体+吹脚 5吹身体.仅在cType=4生效',
master_stat smallint(6) DEFAULT 0 COMMENT '主驾加热状态 0关闭 1 开启 仅在cType=6 7生效',
master_level smallint(6) DEFAULT 0 COMMENT '主驾加热级别 1 低 2 中 3高 仅在cType=6生效',
slave_stat smallint(6) DEFAULT 0 COMMENT '附驾驶加热状态0关闭 1 开启 仅在cType=6 7生效',
slave_level smallint(6) DEFAULT 0 COMMENT '附驾加热级别  1 低 2 中 3高 仅在cType=6生效',
status smallint(1)  COMMENT '状态变化 0：失败 1：成功',
remark varchar(200) COMMENT '备注，错误详细信息',
remark_en varchar(200) COMMENT '英文备注，错误详细信息',
available smallint(1) NOT NULL DEFAULT 1 COMMENT '是否存在, 0 失效 1 有效 默认为1',
ref_id bigint(20) NOT NULL COMMENT 'ref id',
PRIMARY KEY (id),
 FOREIGN KEY (uid) REFERENCES t_user(Id)
) DEFAULT CHARSET=utf8 COMMENT='远程控制指令表';