CREATE TABLE IF NOT EXISTS t_data_realtime_report (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  vin varchar(50) NOT NULL COMMENT 'vin',
  imei varchar(50) NOT NULL COMMENT 'imei',
  application_id int(11) NOT NULL COMMENT 'application id',
  message_id int(11) NOT NULL COMMENT 'message id',
  sending_time DATETIME NOT NULL COMMENT '发送时间',
  driving_time int(11) NOT NULL COMMENT '行驶时间',
  trip_id int(6) NOT NULL COMMENT '电动机启动次数',
  oil_life smallint(6) NOT NULL  COMMENT '机油寿命',
  fuel_oil float NOT NULL COMMENT '燃油量',
  avg_oil_a float NOT NULL COMMENT '平均油耗A',
  avg_oil_b float NOT NULL COMMENT '平均油耗B',
  driving_range int(11) NOT NULL COMMENT '行驶里程',
  mileage_range int(11) NOT NULL  COMMENT '续航里程',
  service_intervall int(11) NOT NULL COMMENT '保养里程',
  left_front_tire_pressure float NOT NULL COMMENT '左前轮胎压',
  left_rear_tire_pressure float NOT NULL COMMENT '左后轮胎压',
  right_front_tire_pressure float NOT NULL COMMENT '右前轮胎压',
  right_rear_tire_pressure float NOT NULL COMMENT '右后轮胎压',
  left_front_window_information varchar(1) NOT NULL COMMENT '左前车窗信息 0开1半开2关3信号异常',
  left_rear_window_information varchar(1) NOT NULL COMMENT '左后车窗信息 0开1半开2关3信号异常',
  right_front_window_information varchar(1) NOT NULL COMMENT '右前车窗信息 0开1半开2关3信号异常',
  right_rear_window_information varchar(1) NOT NULL COMMENT '右后车窗信息 0开1半开2关3信号异常',
  vehicle_temperature float NOT NULL COMMENT '车内温度',
  vehicle_outer_temperature float NOT NULL COMMENT '车外温度',
  left_front_door_information varchar(1) NOT NULL COMMENT '左前车门信息 0开1关2保留3信号异常',
  left_rear_door_information varchar(1) NOT NULL COMMENT '左后车门信息 0开1关2保留3信号异常',
  right_front_door_information varchar(1) NOT NULL COMMENT '右前车门信息 0开1关2保留3信号异常',
  right_rear_door_information varchar(1) NOT NULL COMMENT '右后车门信息 0开1关2保留3信号异常',
  engine_cover_state varchar(1) NOT NULL COMMENT '发动机盖状态 0开1关2保留3信号异常',
  trunk_lid_state varchar(1) NOT NULL COMMENT '后备箱盖状态 0开1关2保留3信号异常',
  skylight_state varchar(1) NOT NULL COMMENT '天窗信息 0开 1半开 2关 3信号异常',
  parking_state varchar(1) NOT NULL COMMENT '驻车状态',
  voltage float NOT NULL COMMENT '蓄电池电压',
  average_speed_a int(5) NOT NULL COMMENT '平均速度A km/h',
  average_speed_b int(5) NOT NULL COMMENT '平均速度B km/h',
  PRIMARY KEY (id),
  INDEX idx_vin(vin),
  INDEX idx_imei(imei),
  INDEX idx_sending_time(sending_time),
  INDEX idx_trip_id(trip_id),
  INDEX idx_driving_time(driving_time),
  INDEX idx_fuel_oil(fuel_oil),
  INDEX idx_avg_oil_a(avg_oil_a),
  INDEX idx_avg_oil_b(avg_oil_b),
  INDEX idx_driving_range(driving_range),
  INDEX idx_mileage_range(mileage_range),
  INDEX idx_service_intervall(service_intervall)
) DEFAULT CHARSET=utf8 COMMENT='实时数据表';

