alter table t_warning_message_conversion add COLUMN group_message_en varchar(150) DEFAULT NULL COMMENT '组消息英文';
insert into t_warning_message_conversion(message_id,message_en,message_zh,group_id,group_message) values('0','','','21','电子换挡器故障');
insert into t_warning_message_conversion(message_id,message_en,message_zh,group_id,group_message) values('0','','','22','电动尾门系统故障');
insert into t_warning_message_conversion(message_id,message_en,message_zh,group_id,group_message) values('0','','','23','前方碰撞预警系统故障');
insert into t_warning_message_conversion(message_id,message_en,message_zh,group_id,group_message) values('0','','','24','紧急制动系统故障');
insert into t_warning_message_conversion(message_id,message_en,message_zh,group_id,group_message) values('0','','','25','车道偏离预警系统故障');
update t_warning_message_conversion set group_message_en='en1' where group_id=1;
update t_warning_message_conversion set group_message_en='en2' where group_id=2;
update t_warning_message_conversion set group_message_en='en3' where group_id=3;
update t_warning_message_conversion set group_message_en='en4' where group_id=4;
update t_warning_message_conversion set group_message_en='en5' where group_id=5;
update t_warning_message_conversion set group_message_en='en6' where group_id=6;
update t_warning_message_conversion set group_message_en='en7' where group_id=7;
update t_warning_message_conversion set group_message_en='en8' where group_id=8;
update t_warning_message_conversion set group_message_en='en9' where group_id=9;
update t_warning_message_conversion set group_message_en='en10' where group_id=10;
update t_warning_message_conversion set group_message_en='en11' where group_id=11;
update t_warning_message_conversion set group_message_en='en12' where group_id=12;
update t_warning_message_conversion set group_message_en='en13' where group_id=13;
update t_warning_message_conversion set group_message_en='en14' where group_id=14;
update t_warning_message_conversion set group_message_en='en15' where group_id=15;
update t_warning_message_conversion set group_message_en='en16' where group_id=16;
update t_warning_message_conversion set group_message_en='en17' where group_id=17;
update t_warning_message_conversion set group_message_en='en18' where group_id=18;
update t_warning_message_conversion set group_message_en='en19' where group_id=19;
update t_warning_message_conversion set group_message_en='en20' where group_id=20;
update t_warning_message_conversion set group_message_en='en21' where group_id=21;
update t_warning_message_conversion set group_message_en='en22' where group_id=22;
update t_warning_message_conversion set group_message_en='en23' where group_id=23;
update t_warning_message_conversion set group_message_en='en24' where group_id=24;
update t_warning_message_conversion set group_message_en='en25' where group_id=25;